### YamlMime:ManagedReference
items:
- uid: BO.Entity.IsComposed
  commentId: T:BO.Entity.IsComposed
  id: IsComposed
  parent: BO.Entity
  children:
  - BO.Entity.IsComposed.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  - BO.Entity.IsComposed.Equals(System.Object)
  - BO.Entity.IsComposed.GetHashCode
  - BO.Entity.IsComposed.IdDish
  - BO.Entity.IsComposed.IdService
  langs:
  - csharp
  - vb
  name: IsComposed
  nameWithType: IsComposed
  fullName: BO.Entity.IsComposed
  type: Class
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: IsComposed
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 12
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\ni\n"
  example: []
  syntax:
    content: public class IsComposed
    content.vb: Public Class IsComposed
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: BO.Entity.IsComposed.IdDish
  commentId: P:BO.Entity.IsComposed.IdDish
  id: IdDish
  parent: BO.Entity.IsComposed
  langs:
  - csharp
  - vb
  name: IdDish
  nameWithType: IsComposed.IdDish
  fullName: BO.Entity.IsComposed.IdDish
  type: Property
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: IdDish
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 17
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\nId du plat\n"
  example: []
  syntax:
    content: public int? IdDish { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public Property IdDish As Integer?
  overload: BO.Entity.IsComposed.IdDish*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BO.Entity.IsComposed.IdService
  commentId: P:BO.Entity.IsComposed.IdService
  id: IdService
  parent: BO.Entity.IsComposed
  langs:
  - csharp
  - vb
  name: IdService
  nameWithType: IsComposed.IdService
  fullName: BO.Entity.IsComposed.IdService
  type: Property
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: IdService
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 21
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\nId du servite \n"
  example: []
  syntax:
    content: public int? IdService { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public Property IdService As Integer?
  overload: BO.Entity.IsComposed.IdService*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BO.Entity.IsComposed.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  commentId: M:BO.Entity.IsComposed.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  id: '#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})'
  parent: BO.Entity.IsComposed
  langs:
  - csharp
  - vb
  name: IsComposed(Nullable<Int32>, Nullable<Int32>)
  nameWithType: IsComposed.IsComposed(Nullable<Int32>, Nullable<Int32>)
  fullName: BO.Entity.IsComposed.IsComposed(System.Nullable<System.Int32>, System.Nullable<System.Int32>)
  type: Constructor
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: .ctor
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 27
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\nConstructeur\n"
  example: []
  syntax:
    content: public IsComposed(int? idDish, int? idService)
    parameters:
    - id: idDish
      type: System.Nullable{System.Int32}
      description: ''
    - id: idService
      type: System.Nullable{System.Int32}
      description: ''
    content.vb: Public Sub New(idDish As Integer?, idService As Integer?)
  overload: BO.Entity.IsComposed.#ctor*
  nameWithType.vb: IsComposed.IsComposed(Nullable(Of Int32), Nullable(Of Int32))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: BO.Entity.IsComposed.IsComposed(System.Nullable(Of System.Int32), System.Nullable(Of System.Int32))
  name.vb: IsComposed(Nullable(Of Int32), Nullable(Of Int32))
- uid: BO.Entity.IsComposed.Equals(System.Object)
  commentId: M:BO.Entity.IsComposed.Equals(System.Object)
  id: Equals(System.Object)
  parent: BO.Entity.IsComposed
  langs:
  - csharp
  - vb
  name: Equals(Object)
  nameWithType: IsComposed.Equals(Object)
  fullName: BO.Entity.IsComposed.Equals(System.Object)
  type: Method
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: Equals
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 37
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\nGénéré automatiquement\n"
  example: []
  syntax:
    content: public override bool Equals(object obj)
    parameters:
    - id: obj
      type: System.Object
      description: ''
    return:
      type: System.Boolean
      description: ''
    content.vb: Public Overrides Function Equals(obj As Object) As Boolean
  overridden: System.Object.Equals(System.Object)
  overload: BO.Entity.IsComposed.Equals*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: BO.Entity.IsComposed.GetHashCode
  commentId: M:BO.Entity.IsComposed.GetHashCode
  id: GetHashCode
  parent: BO.Entity.IsComposed
  langs:
  - csharp
  - vb
  name: GetHashCode()
  nameWithType: IsComposed.GetHashCode()
  fullName: BO.Entity.IsComposed.GetHashCode()
  type: Method
  source:
    remote:
      path: FoodBook/BO/Entity/IsComposed.cs
      branch: main
      repo: https://github.com/Boutanche/FoodBook/
    id: GetHashCode
    path: E:/Fbook/FoodBook/BO/Entity/IsComposed.cs
    startLine: 47
  assemblies:
  - BO
  namespace: BO.Entity
  summary: "\nGénéré automatiquement\n"
  example: []
  syntax:
    content: public override int GetHashCode()
    return:
      type: System.Int32
      description: ''
    content.vb: Public Overrides Function GetHashCode As Integer
  overridden: System.Object.GetHashCode
  overload: BO.Entity.IsComposed.GetHashCode*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: BO.Entity
  commentId: N:BO.Entity
  name: BO.Entity
  nameWithType: BO.Entity
  fullName: BO.Entity
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: BO.Entity.IsComposed.IdDish*
  commentId: Overload:BO.Entity.IsComposed.IdDish
  name: IdDish
  nameWithType: IsComposed.IdDish
  fullName: BO.Entity.IsComposed.IdDish
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullName.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: BO.Entity.IsComposed.IdService*
  commentId: Overload:BO.Entity.IsComposed.IdService
  name: IdService
  nameWithType: IsComposed.IdService
  fullName: BO.Entity.IsComposed.IdService
- uid: BO.Entity.IsComposed.#ctor*
  commentId: Overload:BO.Entity.IsComposed.#ctor
  name: IsComposed
  nameWithType: IsComposed.IsComposed
  fullName: BO.Entity.IsComposed.IsComposed
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: BO.Entity.IsComposed.Equals*
  commentId: Overload:BO.Entity.IsComposed.Equals
  name: Equals
  nameWithType: IsComposed.Equals
  fullName: BO.Entity.IsComposed.Equals
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: BO.Entity.IsComposed.GetHashCode*
  commentId: Overload:BO.Entity.IsComposed.GetHashCode
  name: GetHashCode
  nameWithType: IsComposed.GetHashCode
  fullName: BO.Entity.IsComposed.GetHashCode
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
